### ISSUE TITLE
ImportError - train_model.py

### ISSUE THREAD

**Issue by Tokaran** [arindomjit/Gesture_Detection_CNN#2]
Hi there, apologies if I've messed anything up here - I'm new.

I've been following your tutorial on towards data science and am having an issue with train_model.py. When I run it, I get an ImportError, saying I need to first import keras before using it. Does anyone have any ideas for a fix? I have tried just putting 'import keras' and 'import keras_squeezenet' at the top of the program but it doesn't fix the error. 

```Traceback (most recent call last):
  File "train_model.py", line 3, in <module>
    from keras_squeezenet import SqueezeNet
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_squeezenet\__init__.py", line 2, in <module>
    from keras_squeezenet.squeezenet import SqueezeNet
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_squeezenet\squeezenet.py", line 1, in <module>
    from keras_applications.imagenet_utils import _obtain_input_shape
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_applications\imagenet_utils.py", line 14, in <module>
    backend = get_keras_submodule('backend')
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\keras_applications\__init__.py", line 34, in get_keras_submodule
    raise ImportError('You need to first `import keras` '
ImportError: You need to first `import keras` in order to use `keras_applications`. For instance, you can do:

import keras
from keras_applications import vgg16


Or, preferably, this equivalent formulation:

from keras import applications

**Comment by nhdu** [comment]
Hope this will help!
https://github.com/rcmalli/keras-squeezenet/issues/19
